version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "fgodrop"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-y7balmz9na0d"
s3_prefix = "fgodrop"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
