AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  fgodrop

  Sample SAM Template for fgodrop

  # More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20

Parameters:
  GoogleSheetsApiKey:
    Type: String

Resources:
  FgoDropFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: fgodrop/
      Handler: __main__.handler
      Runtime: python3.11
      Environment:
        Variables:
          GOOGLE_SHEETS_API_KEY: !Ref GoogleSheetsApiKey
      Events:
        FetchFgoDrop:
          Type: Schedule
          Properties:
            Schedule: 'rate(1 hour)'
      Policies:
        - S3FullAccessPolicy:
            BucketName: fgodrop
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: arn:aws:secretsmanager:ap-northeast-1:369646313423:secret:google-sheets-GA2cQS
  FgoDropBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: fgodrop

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  FgoDropFunction:
    Description: "FGO Drop Lambda Function ARN"
    Value: !GetAtt FgoDropFunction.Arn
